Task/integration/87
Web-Masters-Freelancing/Apartment-Management pull request #88
Opened 2024-03-06 07:26 UTC by alOletres

# Issue Link

[Link to the corresponding issue in the github taskboard](https://github.com/orgs/Web-Masters-Freelancing/projects/1/views/1?pane=issue&itemId=55485313)

# Definition of Done

- [x] Users can create category

# Notes
None

# Pre-conditions
run prisma in the server side `npx prisma db push`

# Expected Output
Display of category page and user is able to create category
# Screenshots/Recordings
<img width="960" alt="image" src="https://github.com/Web-Masters-Freelancing/Apartment-Management/assets/94823391/78acf444-2def-4a36-9127-01afd8f38a50">

2024-03-08 10:50 UTC, LodiAniez commented on server/prisma/schema.prisma
> +}
nganong walay relationship sa `Room` na model?

2024-03-10 06:53 UTC, LodiAniez requested changes
borikat, tarungag code

2024-03-10 06:53 UTC, LodiAniez commented on server/prisma/schema.prisma
> +}
pad add ug `isArchived` na column, default value kay false, unsaon nimo pag delete kung wala ni nga column

ayaw idelete kung naay active nga room na gagamit sa category

2024-03-10 06:53 UTC, LodiAniez commented on server/src/category/category.service.ts
> +    return await this.prisma.category.findMany();
```suggestion
    return await this.prisma.category.findMany({
      where: {
        isArchived: false
      }
    });
```

2024-03-10 11:00 UTC, alOletres commented on server/prisma/schema.prisma
> +}
naa na girl

2024-03-14 01:11 UTC, LodiAniez approved these changes

2024-03-14 01:12 UTC, merged